Create Database Intran
Go


USE [Intran]
GO


CREATE TABLE ORDERSTABLE(

ORDERID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

CUSTOMERNAME VARCHAR(30) NOT NULL ,

EMPLOYEENAME VARCHAR(30) NOT NULL ,

ORDERDATE DATETIME NOT NULL DEFAULT GETDATE()

)

 
CREATE TABLE ORDERDETAILSTABLE(

ORDERID INT NOT NULL FOREIGN KEY REFERENCES ORDERSTABLE(ORDERID),

PRODUCTNAME VARCHAR(30) NOT NULL ,

PRICE DECIMAL(7,2) NOT NULL,

QUANTITY INT NOT NULL,


)





BEGIN TRANSACTION

    INSERT INTO ORDERSTABLE(CUSTOMERNAME, EMPLOYEENAME)
    VALUES ('VIKAS','EMP1');

    INSERT INTO ORDERDETAILSTABLE(ORDERID,PRODUCTNAME,PRICE,QUANTITY)
    VALUES (99999,'KEYBOARD',11.20,20);  --THIS COMMAND WILL FAIL

COMMIT TRANSACTION


SELECT * FROM ORDERSTABLE


DELETE FROM ORDERSTABLE



BEGIN TRY

   BEGIN TRANSACTION

		INSERT INTO ORDERSTABLE(CUSTOMERNAME, EMPLOYEENAME)
		VALUES ('VIKAS','EMP1');

		INSERT INTO ORDERDETAILSTABLE(ORDERID,PRODUCTNAME,PRICE,QUANTITY)
		VALUES (99999,'KEYBOARD',11.20,20); 

   COMMIT TRANSACTION

END TRY

BEGIN CATCH

    ROLLBACK TRANSACTION
 

END CATCH;
 
GO

SELECT * FROM ORDERSTABLE
GO

